# Generated by Django 3.0.8 on 2020-07-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('actual', models.IntegerField()),
                ('esperado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=15)),
                ('creacion', models.DateField()),
                ('edicion', models.DateField()),
                ('tipo', models.CharField(choices=[('Misionales', 'Misionales'), ('Operativos', 'Operativos'), ('Apoyo', 'Apoyo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('detalles', models.TextField()),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGC.Procedimiento')),
            ],
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGC.Proceso'),
        ),
    ]
