# Generated by Django 3.0.4 on 2020-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='tipo',
            field=models.CharField(choices=[('misionales', 'Misionales'), ('operativos', 'Operativos'), ('apoyo', 'Apoyo')], max_length=10),
        ),
    ]
