# Generated by Django 3.1.2 on 2020-10-24 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGC', '0003_auto_20201023_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='encargado',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
