# Generated by Django 3.1.2 on 2020-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0004_tarea_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='esperado',
            field=models.IntegerField(null=True),
        ),
    ]
