# Generated by Django 3.1.2 on 2020-10-28 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGC', '0005_auto_20201028_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='encargado',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='esperado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
