# Generated by Django 3.1.2 on 2020-10-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0006_auto_20201028_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='detalles',
            field=models.TextField(blank=True),
        ),
    ]
