# Generated by Django 3.1.2 on 2020-10-30 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGC', '0007_indicador_detalles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='detalles',
            new_name='alcance',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='codigo',
        ),
        migrations.AddField(
            model_name='indicador',
            name='proposito',
            field=models.TextField(default='mejorar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='codigo',
            field=models.CharField(default='COD', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='encargado',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='infograma',
            field=models.ImageField(blank=True, upload_to='infogramas/'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='objetivo',
            field=models.TextField(default='ser mejores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo',
            field=models.CharField(choices=[('misionales', 'Misionales'), ('estrategicos', 'Estrategicos'), ('apoyo', 'Apoyo')], max_length=12),
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
