# Generated by Django 3.1.2 on 2020-10-30 00:17

import SGC.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0008_auto_20201029_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='formatos',
            field=models.FileField(blank=True, upload_to=SGC.models.Procedimiento.foldername),
        ),
    ]
