# Generated by Django 3.1.2 on 2020-10-30 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0009_procedimiento_formatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='detalle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='fecha_objetivo',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 29)),
        ),
        migrations.AddField(
            model_name='indicador',
            name='interpretacion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
