# Generated by Django 3.1.2 on 2020-10-30 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0011_auto_20201029_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='fecha_objetivo',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 30, 4, 17, 24, 429180, tzinfo=utc)),
        ),
    ]
