# Generated by Django 3.1.2 on 2020-10-30 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0012_auto_20201029_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='fecha_objetivo',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
