# Generated by Django 3.1.2 on 2020-10-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0013_auto_20201029_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='procedimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SGC.procedimiento'),
            preserve_default=False,
        ),
    ]
