# Generated by Django 3.1.2 on 2020-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0014_indicador_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='formatos',
            field=models.FileField(blank=True, upload_to='formatos/'),
        ),
    ]
