# Generated by Django 3.1.2 on 2020-12-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGC', '0015_auto_20201206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='formatos',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='infograma',
            field=models.URLField(blank=True),
        ),
    ]
